tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
  - command: |
      cd /workspace/course-python-4-production && source venv/bin/activate

ports:
  - name: server
    description: server
    port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
