tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
  - command: |
      cd /workspace/course-python-4-production && source venv/bin/activate
      echo "PS1='\[[01;32m\]\u\[[00m\] \[[01;34m\]\w\[[00m\] $ '" > ~/.bashrc
      echo "source /workspace/course-python-4-production/venv/bin/activate" > ~/.bashrc

ports:
  - name: server
    description: server
    port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
